# Generated by Django 3.2.3 on 2021-06-22 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('idcomponente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de componente')),
                ('nombrecomponente', models.CharField(max_length=99, verbose_name='Nombre de componente')),
            ],
        ),
        migrations.CreateModel(
            name='fabricante',
            fields=[
                ('idfabricante', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de fabricante')),
                ('nombrefabricante', models.CharField(max_length=99, verbose_name='Nombre de fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreproducto', models.CharField(max_length=99, verbose_name='Nombre de producto')),
                ('precioproducto', models.IntegerField(default=0, verbose_name='Precio del producto')),
                ('componenteproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente', verbose_name='Componente de producto')),
                ('fabricanteproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fabricante', verbose_name='Fabricante del producto')),
            ],
        ),
    ]
