# Generated by Django 3.2.3 on 2021-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenproducto',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stockproducto',
            field=models.IntegerField(default=0, verbose_name='Stock del producto'),
        ),
    ]
